import type { Metadata } from 'next'
import { Onest } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from '@/components/theme-provider'
import Navbar from '@/components/navbar/navbar'
const onest = Onest({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Doctor Chat',
  description: 'Generated by create next app',
  creator: 'Vicente Roa'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={onest.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <Navbar />
          <main>{children}</main>
        </ThemeProvider>
      </body>
    </html>
  )
}
